### PR TITLE
Closed some issues

### PR DESCRIPTION
**Pull request by DeathsGun**
In this PR is closed the following issues:
* Add #10 
* Add #12 
---
I also cleaned up your maven pom.
1. Now you only must change the version number in the pom
2. Resources must be put in the resources dir to work with maven

Regards DeathsGun

### CODE REVIEW

**Comment by cjburkey01** [comment]
Thank you very much! Lazy me is very happy lol

**Comment by DeathsGun** [comment]
@cjburkey01  im currently working on:
* the language system ✅ 
* auto claim ✅ (Not that auto claim in the issue but some better i mean: Toggle  by command and if you walk in a chunk it will be automatically claimed)
* better understandable config ✅

**Comment by cjburkey01** [comment]
I just rewrote the config, oops.

**Comment by cjburkey01** [comment]
Here's the way I've got it:
```
titles:
  useTitlesInsteadOfChat: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20

colors:
  errorColor: RED
  successColor: GREEN
  infoColor: GOLD

chunks:
  maxChunksClaimed: 50
  particlesWhenClaiming: true
  
protection:
  blockPlayerChanges: true
  blockTnt: true
  blockCreeper: true

economy:
  useEconomy: true
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFree: true

dynmap:
  useDynmap: true

messages:
  noPluginPerm: 'You do not have permission to use ClaimChunk.'
  claimNoPerm: 'You do not have permission to claim chunks.'
  claimAlreadyOwned: 'This chunk is already claimed.'
  claimTooMany: 'You own the maximum number of chunks.'
  claimSuccess: 'Chunk claimed!'
  claimFree: 'First chunk is free!'
  claimNotEnoughMoney: 'You do not have enough money.'
  unclaimNoPerm: 'You do not have permission to unclaim chunks.'
  unclaimNotOwned: 'This chunk is not owned.'
  unclaimNotOwner: 'You do not own this chunk.'
  unclaimSuccess: 'Chunk unclaimed!'
  unclaimRefund: 'You have been refunded %%AMT%%.'
  accessNoPerm: 'You do not have permission to give access to chunks.'
  accessHelp: 'Gives <player> access to interact with all blocks in your claimed chunks.'
  accessHas: '%%PLAYER%% now has access to your chunks.'
  accessNoLongerHas: '%%PLAYER%% no longer has access to your chunks.'
  accessNoPlayer: 'That player has not joined the server before.'
  accessOneself: 'You already have access to your own chunks.'
  nameClear: 'Your name has been cleared.'
  nameNotSet: 'You do not have a custom name set.'
  nameSet: 'Your name has been set: %%NAME%%.'
  chunkOwner: 'Entering the territory of %%PLAYER%%.'
  chunkSelf: 'Entering your own territory.'
  chunkLeave: 'Entering unclaimed territory.'
  chunkNoEdit: 'You cannot edit this chunk.'
```

**Comment by DeathsGun** [comment]
My messages were in an own file like en_US.yml

**Comment by cjburkey01** [comment]
Oh, ok, that might actually work better. So, I guess just reset the config and you can implement the language system separately, if that's not too much trouble.

Thanks again for the help 👍

**Comment by DeathsGun** [comment]
ok i will do it tomorrow its 11:36 PM in my country

**Comment by cjburkey01** [comment]
Alright, I'll work on data storage.

**Comment by cjburkey01** [comment]
Might want to hold off for a bit, reworking all of the data storage, and might affect _most things_.

**Pull request merged**
