### PR TITLE
Prevent Claims Within a Distance of Other Users' Claims

### PR DESCRIPTION
**Pull request by JustDoom**
Basically did #106 
If you want any changes please let me know
Also might want to squash the pr if you add it, gradlew doesnt like to work for me

### CODE REVIEW

**Comment by Geolykt** [comment]
There should be an option to disable this given that this is fairly resource-intensive. Additionally I think there should be some "default" value for people that do not have the config up-to-date (how was this solved in the past?)

**Comment by cjburkey01** [comment]
> There should be an option to disable this given that this is fairly resource-intensive. Additionally I think there should be some "default" value for people that do not have the config up-to-date (how was this solved in the past?)

I think whatever option is in the `config.yml` will be the default for anyone who updates to this, a separate option to enable it or setting it to 0 are both options for dealing with it (maybe a 0 check earlier on to ignore the prereq).

**Comment by Geolykt** [comment]
What's your gradle issue anyways? Having potentially untested stuff isn't that good

**Comment by JustDoom** [comment]
> What's your gradle issue anyways? Having potentially untested stuff isn't that good

I have tested it, I used GitHub workflows. Gradle builds once then never again, it says build successful but there is never a new file. This has happened with another thing called Minestom too

**Comment by JustDoom** [comment]
> > There should be an option to disable this given that this is fairly resource-intensive. Additionally I think there should be some "default" value for people that do not have the config up-to-date (how was this solved in the past?)
> 
> I think whatever option is in the `config.yml` will be the default for anyone who updates to this, a separate option to enable it or setting it to 0 are both options for dealing with it (maybe a 0 check earlier on to ignore the prereq).

Setting it to 0 should disable it

**Comment by Goldmensch** [comment]
> > > There should be an option to disable this given that this is fairly resource-intensive. Additionally I think there should be some "default" value for people that do not have the config up-to-date (how was this solved in the past?)
> > 
> > 
> > I think whatever option is in the `config.yml` will be the default for anyone who updates to this, a separate option to enable it or setting it to 0 are both options for dealing with it (maybe a 0 check earlier on to ignore the prereq).
> 
> Setting it to 0 should disable it

It should yeah, but it's better to have a dedicated zero check before it calculate the min and max and instances for loops.

**Comment by Goldmensch** [comment]
> There should be an option to disable this given that this is fairly resource-intensive. Additionally I think there should be some "default" value for people that do not have the config up-to-date (how was this solved in the past?)

Not really resouce-intensive, it's nothing for the VM. But a dedicated zero check is a clearer way to do this.

**Comment by cjburkey01** [comment]
Yep a 0 check would make it more obvious, should the default be 0 to keep default behavior?

**Comment by Geolykt** [comment]
Well, -1 is more or less the default for having something be considered disabled

**Comment by cjburkey01** [comment]
I say just add a check for values <1 and pass the prereq there and it should be good to go?

**Comment by JustDoom** [comment]
done

**Comment by cjburkey01** [comment]
Awesome, I think I should be good to merge, I’ll yeet that in later. Thank you very much!

**Pull request merged**
