### PR TITLE
fixes and other stuff

### PR DESCRIPTION
**Pull request by Goldmensch**
When I tried to use it on my server, I discovered a few more bugs that I hadn't noticed. I hope now adminoverride finally works properly.

### CODE REVIEW

**Comment by cjburkey01** [comment]
All looks good though for the last commit, it would reduce verbosity to include the admin check inside the methods to which we delegated cancelling, there's still one admin check right by where i mean in the world profile around lime 660, but if you swapped from each event method to the methods that they call it would reduce the number of times we need to have the check in the source. there is probably a tiny performance overhead to moving it to another method and you've already done this anyway though so i'm not confident we should even bother switching from what you did here

**Comment by cjburkey01** [comment]
could you remove that admin check though? i'm on my phone rn sorry lol

**Comment by Goldmensch** [comment]
i can't find another temporary admin check lol

**Comment by Goldmensch** [comment]
To your first comment: Should I check it in the "Helper methods", but also only if it is enabled? Or do I understand this wrong?

**Comment by cjburkey01** [comment]
Oh maybe you got it in your commit and i missed it lol, but the checks could happen inside of the private helper methods in the world profile event handler class and there would be fewer places to keep track of it

**Comment by Goldmensch** [comment]
Ah ok I know what you mean. Only I would change the order of the helper methods, so that it first checks if the profile is enabled and then does everything else. Otherwise it checks or calculates useless things that it doesn't need anyway. Or would this break something?

**Comment by Goldmensch** [comment]
And should you bypass blocked commands with admin override?

**Comment by Goldmensch** [comment]
Eine Frage noch, warum erstellst du jedes mal eine neue runnable wenn du die helper methoden aufrufst? Währe es nicht schlauer einfach den boolean ob es gecancelt werden soll zu übergeben?

**Comment by Goldmensch** [comment]
cj has you forgot about me? xD @cjburkey01

**Comment by Goldmensch** [comment]
(soliloquy) Oh nick, why do you always have to write "last" instead of "latest"

**Pull request merged**
