### PR TITLE
Scan command and couple other things

### PR DESCRIPTION
**Pull request by JustDoom**
Added a command to scan for nearby claims, goes well with the last pr I made. 
Permission is "claimchunk.scan"
It skips over your own claims, I can change this if you want
Made a config option to limit how far you can scan, anything over 25-30 has a risk of crashing your server/lagging it a lot

Also added a bypass permission for admins so they can claim next to others claims if the option is enabled
Fixed the names of the config option I added last time too, had - in-between words instead of using camelCase

I was going to add it so people with building permissions on a claim could claim next to it but couldn't find how to check if you had build perms

### CODE REVIEW

**Comment by JustDoom** [comment]
probably squish the pr maybe

**Comment by JustDoom** [comment]
aw got conflicts now

**Comment by cjburkey01** [comment]
oh dang where are they conflicting? i'm on mobile but is it a simple fix for you or me?

**Comment by JustDoom** [comment]
```
src/main/java/com/cjburkey/claimchunk/Messages.java
src/main/java/com/cjburkey/claimchunk/service/prereq/claim/NearChunkPrereq.java
src/main/resources/plugin.yml
```

I'll try and fix them this afternoon, shouldnt be too hard

**Comment by cjburkey01** [comment]
Cool, let me know once that's working and i'll merge it

**Comment by cjburkey01** [comment]
OH, yeah i renamed the messages class and it's moved! that's what happened, should still work the same it's in the i18n package

**Comment by JustDoom** [comment]
@cjburkey01 
done

**Comment by cjburkey01** [comment]
Awesome, will merge tomorrow when im able to double check it all goes smoothly

**Comment by cjburkey01** [comment]
Ok for one last thing, did you add a specific entry for `claimchunk.bypassnearbychunk` anywhere in the `plugin.yml`? I see you added it to admin but I don't see the entry where it gets a description and such (could be me missing it)

**Comment by JustDoom** [comment]
Oops, Ill add that

**Comment by JustDoom** [comment]
@cjburkey01

**Pull request merged**
