### PR TITLE
Build the Plugin via Github Actions + Update gradle Version to 7.0

### PR DESCRIPTION
**Pull request by T0biii**
Create gradle.yml for auto build with Github Actions

- Build works there (https://github.com/T0biii/ClaimChunk/pull/1/checks?check_run_id=2493385363, https://github.com/T0biii/ClaimChunk/actions)
- You can Download the .jar afterwards (Artifact) (.zip)
- Update gradle Version to 7.0

### CODE REVIEW

**Comment by T0biii** [comment]
Maybe it works better? i dunno

**Comment by Geolykt** [comment]
This plugin does not build correctly inside Github CI most of the times. I wouldn't consider this to be worth the trouble as it is unreliable at best.
I honestly think that someone should investigate the exact cause of this issue, but this is all up to the author of this repo

**Comment by T0biii** [comment]
atm the Build works for me.
Here some wired fixes: https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse
Also someone in the comments mentioned that JDK11 maybe can be a problem (https://stackoverflow.com/a/58981695)
The Github CI runs with Java 8 (https://github.com/T0biii/ClaimChunk/blob/T0biii-patch-1/.github/workflows/gradle.yml#L22). 

Maybe he want to run Travis and GitHub parallel

**Comment by cjburkey01** [comment]
> This plugin does not build correctly inside Github CI most of the times. I wouldn't consider this to be worth the trouble as it is unreliable at best.
> 
> I honestly think that someone should investigate the exact cause of this issue, but this is all up to the author of this repo

I've had so much trouble with this too XD

The best solution Ive found is giving it time and trying later, I think it's something weird with the WorldGuard and WorldEdit repos because sometimes Gradle complains it can't access them even though I can use a browser request to view them manually 🙄

**Comment by cjburkey01** [comment]
Also thank you for this auto build, is there a fun Github URL I could use for like "latest snapshot build" as a direct download?

**Comment by cjburkey01** [comment]
> atm the Build works for me.
> 
> Here some wired fixes: https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse
> 
> Also someone in the comments mentioned that JDK11 maybe can be a problem (https://stackoverflow.com/a/58981695)
> 
> The Github CI runs with Java 8 (https://github.com/T0biii/ClaimChunk/blob/T0biii-patch-1/.github/workflows/gradle.yml#L22). 
> 
> 
> 
> Maybe he want to run Travis and GitHub parallel 

Oh is 11 being used somewhere? CC should build on 8 so if I'm using 11 anywhere I don't mean to be yet

**Comment by T0biii** [comment]
> Oh is 11 being used somewhere? CC should build on 8 so if I'm using 11 anywhere I don't mean to be yet

https://travis-ci.com/github/cjburkey01/ClaimChunk/builds/224049519#L191
javac 11.0.2

so travis-ci is using java 11 or?

**Comment by Geolykt** [comment]
Speaking of build failures dependent on java versions, someone should update the gradle wrapper to gradle 7 to allow for Java 16 compat (*especially since it has been out for some time now*). Gradle does not want to work with up-to date java versions.

**Comment by T0biii** [comment]
> Also thank you for this auto build, is there a fun Github URL I could use for like "latest snapshot build" as a direct download?

im not sure if there is a link, but you can create a workflow that builds the jar and create a release and upload the artefact to the release if you push a tag. Something like there: https://github.com/freifunkMUC/site-ffm/blob/stable/.github/workflows/firmware.yml

**Comment by T0biii** [comment]
> Speaking of build failures dependent on java versions, someone should update the gradle wrapper to gradle 7 to allow for Java 16 compat (_especially since it has been out for some time now_). Gradle does not want to work with up-to date java versions.
> 
> That being said, I almost exclusively compile this plugin with AdoptOpenJDK 15 and it works just as intended

mmh you can use `./gradlew wrapper --gradle-version=7.0 --distribution-type=bin` to Uprade to gradle 7 (https://gradle.org/install/#with-the-gradle-wrapper)

**Comment by cjburkey01** [comment]
> https://travis-ci.com/github/cjburkey01/ClaimChunk/builds/224049519#L191
> 
> javac 11.0.2
> 
> 
> 
> so travis-ci is using java 11 or?

oh yes it is, hm. should i move towards 11 source compat or stick to 8? idk the convention with newer java versions

**Comment by cjburkey01** [comment]
> > Speaking of build failures dependent on java versions, someone should update the gradle wrapper to gradle 7 to allow for Java 16 compat (_especially since it has been out for some time now_). Gradle does not want to work with up-to date java versions.
> 
> > 
> 
> > That being said, I almost exclusively compile this plugin with AdoptOpenJDK 15 and it works just as intended
> 
> 
> 
> mmh you can use `./gradlew wrapper --gradle-version=7.0 --distribution-type=bin` to Uprade to gradle 7 (https://gradle.org/install/#with-the-gradle-wrapper)

I can do that when I get home or do you wanna add it onto this pr?

**Comment by T0biii** [comment]
> > [travis-ci.com/github/cjburkey01/ClaimChunk/builds/224049519#L191](https://travis-ci.com/github/cjburkey01/ClaimChunk/builds/224049519#L191)
> > javac 11.0.2
> > so travis-ci is using java 11 or?
> 
> oh yes it is, hm. should i move towards 11 source compat or stick to 8? idk the convention with newer java versions

good Question, i moving to Java 11 or newer with my Plugins when paper 1.17 is released, because Paper 1.17 only supports Java 11 or newer (https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615)

**Comment by T0biii** [comment]
> > > Speaking of build failures dependent on java versions, someone should update the gradle wrapper to gradle 7 to allow for Java 16 compat (_especially since it has been out for some time now_). Gradle does not want to work with up-to date java versions.
> > 
> > 
> > > 
> > 
> > 
> > > That being said, I almost exclusively compile this plugin with AdoptOpenJDK 15 and it works just as intended
> > 
> > 
> > mmh you can use `./gradlew wrapper --gradle-version=7.0 --distribution-type=bin` to Uprade to gradle 7 ([gradle.org/install/#with-the-gradle-wrapper](https://gradle.org/install/#with-the-gradle-wrapper))
> 
> I can do that when I get home or do you wanna add it onto this pr?

i commited the requestet change already

**Pull request merged**
